#!/bin/sh

# these versions are tag names
export ENGINEBLOCK_VERSION=develop
export API_VERSION=master
export MANAGE_VERSION=master
export SERVICEREGISTRY_VERSION=develop
export STATIC_VERSION=develop
# Teams still on 3.3.0, until Grouper upgrade is available on VM
export TEAMS_VERSION=coin-teams-parent-3.3.0
export MUJINA_VERSION=master
export CRUNCHER_VERSION=master
export APIS_VERSION=master
export CSA_VERSION=master

# these are _not_ tag names
export GROUPER_VERSION=2.8.0
