#!/bin/sh

# these versions are tag names
export ENGINEBLOCK_VERSION=develop
export API_VERSION=master
export MANAGE_VERSION=develop
export SERVICEREGISTRY_VERSION=develop
export STATIC_VERSION=develop
export TEAMS_VERSION=master
export MUJINA_VERSION=master
export CRUNCHER_VERSION=master
export APIS_VERSION=master
export CSA_VERSION=master

# these are _not_ tag names
export GROUPER_VERSION=2.8.0
