#!/bin/sh

# these versions are tag names
export ENGINEBLOCK_VERSION=3.5.0
export API_VERSION=coin-api-parent-3.5.1
export MANAGE_VERSION=3.0.0
export SERVICEREGISTRY_VERSION=3.5.0
export STATIC_VERSION=static-v2.12.2
export TEAMS_VERSION=coin-teams-parent-3.3.0
export MUJINA_VERSION=mujina-2.15.1

# these are _not_ tag names
export GROUPER_VERSION=2.8.0