#!/bin/sh

# these versions are tag names
export ENGINEBLOCK_VERSION=3.5.0
export API_VERSION=coin-api-parent-3.6.1
export MANAGE_VERSION=3.0.0
export SERVICEREGISTRY_VERSION=3.5.0
export STATIC_VERSION=static-v2.12.2
export TEAMS_VERSION=coin-teams-parent-3.3.0
export MUJINA_VERSION=mujina-2.15.1

#export CRUNCHER_VERSION=3.6.3
#export CSA_VERSION=3.6.3
#export APIS_VERSION=1.3.2
export CRUNCHER_VERSION=master
export CSA_VERSION=master
export APIS_VERSION=master

# these are _not_ tag names
export GROUPER_VERSION=2.8.0
