#!/usr/bin/env ruby
#^syntax detection

role "openconext-engineblock",
    git: "git@github.com:OpenConext/OpenConext-engineblock.git",
    ref: "feature/ansible",
    path: "./tools/ansible-role-openconext-engineblock"

role "openconext-api",
    git: "git@github.com:OpenConext/OpenConext-api.git",
    ref: "feature/ansible",
    path: "./coin-api-dist/src/main/ansible"

role "ansible-xml",
    github: "relaxnow/ansible-xml"