---
  - name: "BUILD - Legacy: Remove obsolete profile.d/openconext.sh"
    file: path=/etc/profile.d/openconext.sh state=absent

  - name: "BUILD - Legacy: Move /var/log/surfconext to /var/log/openconext"
    command: mv /var/log/surfconext {{ logging_dir }}
    ignore_errors: yes

  - name: "BUILD - Install logging directory"
    file: path={{ logging_dir }} state=directory

  - name: "BUILD - Legacy: Install symlink from /var/log/surfconext to /var/log/openconext"
    file: path=/var/log/surfconext src={{ logging_dir }} state=link