---
  - name: SRC - Install Git repo
    git:
      accept_hostkey: yes
      repo: "{{ api_git_url }}"
      dest: "{{ api_release_dir }}"
      version: "{{ api_version }}"

  - name: SRC - Running Maven install
    command: mvn -q clean install -DskipTests
    args:
      chdir: "{{ api_release_dir }}"

  - name: SRC - Find built dists
    shell: ls {{ api_release_dir }}/coin-api-dist/target/coin-api-dist-*-bin.tar.gz
    register: dist
    failed_when: "dist.stdout_lines|length != 1"
    changed_when: False

  - name: SRC - Copy build to build directory
    copy:
      src: "{{ dist.stdout }}"
      dest: "{{ api_build_path }}"