#! /bin/bash
##################################################################################################
#                                                                                                #
# Configuration and Credentials file for OpenConext                                              #
#                                                                                                #
##################################################################################################
#    
#
# This file holds the default configuration and credentials.
# Passwords are set with standard values in this script, THIS IS NOT SAFE!!!, 
# change them either to values you configured previously, or run script XYZ 
# to seed the values with random values
#
# Usernames may be changed, but only if it's not mentioned in the notes
# Use strong passwords, generate them via shell with:
# tr -c -d '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ' </dev/urandom | dd bs=15 count=1 2>/dev/null;echo
#
# TODO: replace with script for password setting

# The default domain will be used as the base domain for all components.
# Components will be named XYZ.DEFAULT_DOMAIN, so e.g. engine.demo.openconext.org
DEFAULT_DOMAIN=demo.openconext.org

# This is the default set of components in an install
# Available components are: EB SR MANAGE API TEAMS MUJINA GROUPER APIS CRUNCHER CSA DASHBOARD 
# (v62, 2014-03-03)
DEFAULT_OC_COMPONENTS="EB SR MANAGE API TEAMS MUJINA GROUPER"

# When installing OpenConext a new CA is created. The passsword for the CA private key is set here
CA_KEY_PASSWORD=mysecret

# The Admin name and email adress for this installation to use as default mail adress
OC__ADMIN_NAME="OpenConext Administrator"
OC__ADMIN_EMAIL="openconext@example.org"

# Default timezone
OC__TIMEZONE = "Europe/Amsterdam"


##################################################################################################
#                                                                                                #    
# MySQL database users and passwords                                                             #
#                                                                                                #
##################################################################################################
#
# This section defines username and passwords for various components that need the mysql database. 
# For a decription of the various components see https://www.openconext.org

# New MySQL root password
OC__ROOT_DB_PASS="rootpassw0rd"

# New MySQL engine user and password
OC__ENGINE_DB_USER="engine2mysql"
OC__ENGINE_DB_PASS="enginepass"

# New MySQL serviceregistry (JANUS) user and password
OC__SERVICEREGISTRY_DB_USER="sr2mysql"
OC__SERVICEREGISTRY_DB_PASS="srpass"

# New MySQL manage user and password
OC__MANAGE_DB_USER="manage2mysql"
OC__MANAGE_DB_PASS="managepass"

# New MySQL teams user and password
OC__TEAMS_DB_USER="teams2mysql"
OC__TEAMS_DB_PASS="teamspass"

# New MySQL api user and password
OC__API_DB_USER="api2mysql"
OC__API_DB_PASS="apipass"

##################################################################################################
#                                                                                                #    
# ServiceRegistry (JANUS)                                                                        #
#                                                                                                #
##################################################################################################
#
# This section sets the credentials for the simplesaml install that is the basis for ServiceRegistry (Janus)
# 
# This section also sets the credentials for the ServiceRegistry REST API clients
# These users will be set in MySQL database 'serviceregistry.janus__user'

# Serviceregistry (JANUS) local admin password
# The adminpass is the localadmin login for JANUS (simplesamlphp)
# Local admin login can only be used when authsource is set to 'auth' -> 'admin' and 'useridattr' -> 'user'
# This can be done in /etc/surfconext/serviceregistry.module_janus.php and is already preconfigured
janusadmin_pass="januspass"

# This is a secret salt used by simpleSAMLphp (JANUS) when it needs to generate a secure hash of a value.
# Use a strong secret salt, this can be a valid string of any length
# A possible way to generate a random salt is by running the following command from a unix shell:
# tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | dd bs=32 count=1 2>/dev/null;echo
janus_secretsalt="janussecret"

# Serviceregistry (JANUS) API user for 'engineblock'
# Warning: do not change the value of engineblock_janusapi_user, value has to be "engine" in current script!
OC__ENGINE_JANUSAPI_USER="engine"
OC__ENGINE_JANUSAPI_PASS="enginejanuspass"


# Serviceregistry (JANUS) API user for 'api'
# Warning: api user is at the moment also named 'engine' user because api user doesn't exist yet.
OC__API_JANUSAPI_USER="engine"
OC__API_JANUSAPI_PASS="enginejanuspass"

##################################################################################################
#                                                                                                #    
# Grouper (client) users and passwords                                                                       #
#                                                                                                #
##################################################################################################
#
# Grouper is used by engine, api and teams to store group information
# Client credentials are stored in tomcat's tomcat-users.xml file
OC__GROUPER_SYSTEM_USER="GrouperSystem"
OC__GROUPER_SYSTEM_PASS="Ah75DGe8Ef"

OC__GROUPER_ENGINE_USER="engine"
OC__GROUPER_ENGINE_PASS="KJ75DFeg32a"

# TODO: NO API user credentials????
OC__GROUPER_API_USER="engine"
OC__GROUPER_API_PASS="KJ75DFeg32a"

OC__GROUPER_UNIT_TEST_USER="gadget"
OC__GROUPER_UNIT_TEST_PASS="7453E1E58216"


##################################################################################################
#                                                                                                #    
# LDAP users and passwords                                                                       #
#                                                                                                #
##################################################################################################
#
# LDAP is used by engine, grouper and api to store user profile information

OC__LDAP_USER="cn=ro,dc=surfconext,dc=nl"
OC__LDAP_PASS="ldappass"

